model_job_hourly:
  ops:
    model_trained:
      config:
        batch_size: 128
        epochs: 15
        learning_rate: 0.001
        embeddings_dim: 5


mlflow:
  experiment_name: "recommender_system"
  
